title: 少数派报告----Edward's Webblog
description: Some raw thought.
author: Edward Yuan
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
