encoding: UTF-8
name: Edward Yuan
url: http://edwardyuan.github.io
description: Edward's Blog —— some raw thought.

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
