encoding: UTF-8
name: 少数派报告
url: http://edwardyuan.github.io
description: Some raw thought.

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
